# Generated by Django 5.2.4 on 2025-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_quantity', models.IntegerField()),
                ('p_price', models.IntegerField()),
                ('p_discount', models.IntegerField()),
            ],
        ),
    ]
