# Generated by Django 5.2.4 on 2025-07-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='Item',
        ),
    ]
