# Generated by Django 5.2.4 on 2025-07-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_remove_bill_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
